version: '3'
 
services:
    django:
        build: ./django
        container_name: django
        command: uwsgi --socket :8001 --module memorialnotify.wsgi --py-autoreload 1 
        volumes: 
        - ./src:/memofy
        - ./static:/static
        expose:
        - "8001"
        depends_on:
        - db
    db:
        image: mysql:5.7
        container_name: mysql
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        env_file: .env
        environment:
            TZ: 'Asia/Tokyo'   
        volumes:
            - mysql-db:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
    nginx:
        image: nginx:1.13
        container_name: nginx
        ports:
        - "8000:8000"
        volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
        - ./static:/static
        depends_on:
        - django
volumes:
    mysql-db:
        driver: local
